# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.5
default_acceleration_scaling_factor: 0.5

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  # Left arm joints
  left_Revolute_1:
    has_velocity_limits: true
    max_velocity: 30.0
    has_acceleration_limits: true
    max_acceleration: 50.0
  left_Revolute_2:
    has_velocity_limits: true
    max_velocity: 30.0
    has_acceleration_limits: true
    max_acceleration: 50.0
  left_Revolute_3:
    has_velocity_limits: true
    max_velocity: 30.0
    has_acceleration_limits: true
    max_acceleration: 50.0
  left_Revolute_4:
    has_velocity_limits: true
    max_velocity: 30.0
    has_acceleration_limits: true
    max_acceleration: 50.0
  left_Revolute_5:
    has_velocity_limits: true
    max_velocity: 30.0
    has_acceleration_limits: true
    max_acceleration: 50.0
  left_Revolute_6:
    has_velocity_limits: true
    max_velocity: 30.0
    has_acceleration_limits: true
    max_acceleration: 50.0
  left_Slider_1:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: true
    max_acceleration: 50.0
  left_Slider_2:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: true
    max_acceleration: 50.0
    
  # Right arm joints
  right_Revolute_1:
    has_velocity_limits: true
    max_velocity: 30.0
    has_acceleration_limits: true
    max_acceleration: 50.0
  right_Revolute_2:
    has_velocity_limits: true
    max_velocity: 30.0
    has_acceleration_limits: true
    max_acceleration: 50.0
  right_Revolute_3:
    has_velocity_limits: true
    max_velocity: 30.0
    has_acceleration_limits: true
    max_acceleration: 50.0
  right_Revolute_4:
    has_velocity_limits: true
    max_velocity: 30.0
    has_acceleration_limits: true
    max_acceleration: 50.0
  right_Revolute_5:
    has_velocity_limits: true
    max_velocity: 30.0
    has_acceleration_limits: true
    max_acceleration: 50.0
  right_Revolute_6:
    has_velocity_limits: true
    max_velocity: 30.0
    has_acceleration_limits: true
    max_acceleration: 50.0
  right_Slider_1:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: true
    max_acceleration: 50.0
  right_Slider_2:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: true
    max_acceleration: 50.0

  # Seiretu joints (separate from arm control)
  