# This config file is used by ros2_control with Gazebo

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    joints:
      - left_Revolute_1
      - left_Revolute_2
      - left_Revolute_3
      - left_Revolute_4
      - left_Revolute_5
      - left_Revolute_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    action_ns: follow_joint_trajectory
    allow_partial_joints_goal: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

right_arm_controller:
  ros__parameters:
    joints:
      - right_Revolute_1
      - right_Revolute_2
      - right_Revolute_3
      - right_Revolute_4
      - right_Revolute_5
      - right_Revolute_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    action_ns: follow_joint_trajectory
    allow_partial_joints_goal: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

left_hand_controller:
  ros__parameters:
    joints:
      - left_Slider_1
      - left_Slider_2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    action_ns: follow_joint_trajectory
    allow_partial_joints_goal: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

right_hand_controller:
  ros__parameters:
    joints:
      - right_Slider_1
      - right_Slider_2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    action_ns: follow_joint_trajectory
    allow_partial_joints_goal: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

joint_state_broadcaster:
  ros__parameters:
    use_local_topics: false