# Default initial positions for arm's ros2_control fake system

initial_positions:
  Revolute_1: 0.0
  Revolute_2: 0.0
  Revolute_3: 0.0
  Revolute_4: 0.0
  Revolute_5: 0.0
  Revolute_6: 0.0
  Slider_1: 0.0
  Slider_2: 0.0