# Default initial positions for 0525_arm's ros2_control fake system

initial_positions:
  Revolute 1: 0.0  # ★ 0 から 0.0 に変更
  Revolute 2: 0.0  # ★ 0 から 0.0 に変更
  Revolute 3: 0.0  # ★ 0 から 0.0 に変更
  Revolute 4: 0.0  # ★ 0 から 0.0 に変更
  Revolute 5: 0.0  # ★ 0 から 0.0 に変更
  Revolute 6: 0.0  # ★ 0 から 0.0 に変更
  Slider 1: 0.0    # ★ 0 から 0.0 に変更
  Slider 2: 0.0    # ★ 0 から 0.0 に変更