# Initial positions for left arm's ros2_control fake system

initial_positions:
  left_Revolute_1: 0.0
  left_Revolute_2: 0.0
  left_Revolute_3: 0.0
  left_Revolute_4: 0.0
  left_Revolute_5: 1.57
  left_Revolute_6: 0.0
  left_Slider_1: 0.0
  left_Slider_2: 0.0