planning_plugin: ompl_interface/OMPLPlanner
start_state_max_bounds_error: 0.1
jiggle_fraction: 0.05
request_adapters: >-
    default_planner_request_adapters/AddTimeOptimalParameterization
    default_planner_request_adapters/ResolveConstraintFrames
    default_planner_request_adapters/FixWorkspaceBounds
    default_planner_request_adapters/FixStartStateBounds
    default_planner_request_adapters/FixStartStateCollision
    default_planner_request_adapters/FixStartStatePathConstraints

planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0
              default_planning_pipeline="ompl"
  RRTstarkConfigDefault:
    type: geometric::RRTstar
    delay_collision_checking: 1
    goal_bias: 0.05
    range: 0.0
    
  BFMTkConfigDefault:
    type: geometric::BFMT
    k_nearest: 1
    radius_multiplier: 1.0
    seed: 0
    optimization_objective: PathLengthOptimizationObjective
    heuristics: 0
    heuristics_radius: 1.0
    number_sampling_attempts: 1000
    
  PRMkConfigDefault:
    type: geometric::PRM
    max_nearest_neighbors: 10
    
  PRMstarkConfigDefault:
    type: geometric::PRMstar

arm:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - BFMTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
  projection_evaluator: joints(Revolute_1,Revolute_2)
  longest_valid_segment_fraction: 0.01