# RealSense Camera Parameters Template
# This file will be used as a template for multiple cameras
camera_node:
  ros__parameters:
    # Device selection
    serial_no: ""  # Will be overridden per camera
    device_type: "d435i"
    
    # Camera naming
    camera_name: "camera"  # Will be overridden per camera
    camera_namespace: "camera"  # Will be overridden per camera
    
    # Basic settings
    initial_reset: true
    wait_for_device_timeout: 5.0
    reconnect_timeout: 6.0
    
    # Stream enablement
    enable_color: true
    enable_depth: true
    enable_infra: false
    enable_infra1: false
    enable_infra2: false
    enable_gyro: true
    enable_accel: true
    enable_sync: true
    
    # Stream profiles
    rgb_camera.color_profile: "640,480,30"
    depth_module.depth_profile: "640,480,30"
    
    # Processing options
    align_depth.enable: true
    pointcloud.enable: true
    pointcloud.stream_filter: 2
    pointcloud.stream_index_filter: 0
    pointcloud.ordered_pc: false
    pointcloud.allow_no_texture_points: false
    
    # Transform publishing
    publish_tf: true
    tf_publish_rate: 0.0
    base_frame_id: "link"
    tf_prefix: ""
    
    # Auto exposure
    rgb_camera.enable_auto_exposure: true
    depth_module.enable_auto_exposure: true
    
    # Filters (disabled by default for performance)
    decimation_filter.enable: false
    spatial_filter.enable: false
    temporal_filter.enable: false
    hole_filling_filter.enable: false
    colorizer.enable: false
    
    # Diagnostics
    diagnostics_period: 0.0
    
    # Motion settings
    unite_imu_method: 0
    angular_velocity_cov: 0.01
    linear_accel_cov: 0.01
    
    # Depth settings
    clip_distance: -2.0