# This config file is used by ros2_control

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      ros__parameters:
        joints:
          - Revolute_1
          - Revolute_2
          - Revolute_3
          - Revolute_4
          - Revolute_5
          - Revolute_6
          - Slider_1
          - Slider_2

arm_controller:
  ros__parameters:
    joints:
      - Revolute_1
      - Revolute_2
      - Revolute_3
      - Revolute_4
      - Revolute_5
      - Revolute_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    action_ns: follow_joint_trajectory
hand_controller:
  ros__parameters:
    joints:
      - Slider_1
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    action_ns: follow_joint_trajectory
